

all: 	\
		coach1 \
		coach2 \
		coach3 \
		coach4 \
		mysort \
		quick \
		heap

quick: quick.c
		gcc -Wall quick.c -o quick

heap: heap.c
		gcc -Wall heap.c -o heap


coach1: coach1.c
		gcc -Wall coach1.c -o coach1


coach2: coach2.c
		gcc -Wall coach2.c -o coach2

coach3:	coach3.c
		gcc -Wall coach3.c -o coach3

coach4: coach4.c
		gcc -Wall coach4.c -o coach4

mysort: mysort.c
		gcc -Wall mysort.c -o mysort
